# Generated by Django 6.0.7 on 2026-08-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_alter_employee_id_alter_profile_id_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='submission',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
